from django.db import models

# Create your models here.
class canal1(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()
    V2 = models.FloatField()
    V3 = models.FloatField()
    VB12 = models.FloatField()
    VB23 = models.FloatField()
    VB31 = models.FloatField()
    C1 = models.FloatField()
    C2 = models.FloatField()
    C3 = models.FloatField()
    AP1 = models.FloatField()
    AP2 = models.FloatField()
    AP3 = models.FloatField()
    TAP = models.FloatField()
    ApP1 = models.FloatField()
    ApP2 = models.FloatField()
    ApP3 = models.FloatField()
    TApP = models.FloatField()
    R1 = models.FloatField()
    R2 = models.FloatField()
    R3 = models.FloatField()
    TRP = models.FloatField()
    PF1 = models.FloatField()
    PF2 = models.FloatField()
    PF3 = models.FloatField()
    TPF = models.FloatField()
    F1 = models.FloatField()
    F2 = models.FloatField()
    F3 = models.FloatField()
    CN = models.FloatField()
    PF1C = models.FloatField()
    PF2C = models.FloatField()
    PF3C = models.FloatField()
    TPFS = models.FloatField()
    TC = models.FloatField()
    LC = models.FloatField()



class canal2(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()
    V2 = models.FloatField()
    V3 = models.FloatField()
    VB12 = models.FloatField()
    VB23 = models.FloatField()
    VB31 = models.FloatField()
    C1 = models.FloatField()
    C2 = models.FloatField()
    C3 = models.FloatField()
    AP1 = models.FloatField()
    AP2 = models.FloatField()
    AP3 = models.FloatField()
    TAP = models.FloatField()
    ApP1 = models.FloatField()
    ApP2 = models.FloatField()
    ApP3 = models.FloatField()
    TApP = models.FloatField()
    R1 = models.FloatField()
    R2 = models.FloatField()
    R3 = models.FloatField()
    TRP = models.FloatField()
    PF1 = models.FloatField()
    PF2 = models.FloatField()
    PF3 = models.FloatField()
    TPF = models.FloatField()
    F1 = models.FloatField()
    F2 = models.FloatField()
    F3 = models.FloatField()
    CN = models.FloatField()
    PF1C = models.FloatField()
    PF2C = models.FloatField()
    PF3C = models.FloatField()
    TPFS = models.FloatField()
    TC = models.FloatField()
    LC = models.FloatField()


class canal3(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()
    V2 = models.FloatField()
    V3 = models.FloatField()
    VB12 = models.FloatField()
    VB23 = models.FloatField()
    VB31 = models.FloatField()
    C1 = models.FloatField()
    C2 = models.FloatField()
    C3 = models.FloatField()
    AP1 = models.FloatField()
    AP2 = models.FloatField()
    AP3 = models.FloatField()
    TAP = models.FloatField()
    ApP1 = models.FloatField()
    ApP2 = models.FloatField()
    ApP3 = models.FloatField()
    TApP = models.FloatField()
    R1 = models.FloatField()
    R2 = models.FloatField()
    R3 = models.FloatField()
    TRP = models.FloatField()
    PF1 = models.FloatField()
    PF2 = models.FloatField()
    PF3 = models.FloatField()
    TPF = models.FloatField()
    F1 = models.FloatField()
    F2 = models.FloatField()
    F3 = models.FloatField()
    CN = models.FloatField()
    PF1C = models.FloatField()
    PF2C = models.FloatField()
    PF3C = models.FloatField()
    TPFS = models.FloatField()
    TC = models.FloatField()
    LC = models.FloatField()



class canal4(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()
    V2 = models.FloatField()
    V3 = models.FloatField()
    VB12 = models.FloatField()
    VB23 = models.FloatField()
    VB31 = models.FloatField()
    C1 = models.FloatField()
    C2 = models.FloatField()
    C3 = models.FloatField()
    AP1 = models.FloatField()
    AP2 = models.FloatField()
    AP3 = models.FloatField()
    TAP = models.FloatField()
    ApP1 = models.FloatField()
    ApP2 = models.FloatField()
    ApP3 = models.FloatField()
    TApP = models.FloatField()
    R1 = models.FloatField()
    R2 = models.FloatField()
    R3 = models.FloatField()
    TRP = models.FloatField()
    PF1 = models.FloatField()
    PF2 = models.FloatField()
    PF3 = models.FloatField()
    TPF = models.FloatField()
    F1 = models.FloatField()
    F2 = models.FloatField()
    F3 = models.FloatField()
    CN = models.FloatField()
    PF1C = models.FloatField()
    PF2C = models.FloatField()
    PF3C = models.FloatField()
    TPFS = models.FloatField()
    TC = models.FloatField()
    LC = models.FloatField()
    
class canal5(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()
    V2 = models.FloatField()
    V3 = models.FloatField()
    VB12 = models.FloatField()
    VB23 = models.FloatField()
    VB31 = models.FloatField()
    C1 = models.FloatField()
    C2 = models.FloatField()
    C3 = models.FloatField()
    AP1 = models.FloatField()
    AP2 = models.FloatField()
    AP3 = models.FloatField()
    TAP = models.FloatField()
    ApP1 = models.FloatField()
    ApP2 = models.FloatField()
    ApP3 = models.FloatField()
    TApP = models.FloatField()
    R1 = models.FloatField()
    R2 = models.FloatField()
    R3 = models.FloatField()
    TRP = models.FloatField()
    PF1 = models.FloatField()
    PF2 = models.FloatField()
    PF3 = models.FloatField()
    TPF = models.FloatField()
    F1 = models.FloatField()
    F2 = models.FloatField()
    F3 = models.FloatField()
    CN = models.FloatField()
    PF1C = models.FloatField()
    PF2C = models.FloatField()
    PF3C = models.FloatField()
    TPFS = models.FloatField()
    TC = models.FloatField()
    LC = models.FloatField()

class canal6(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()
    V2 = models.FloatField()
    V3 = models.FloatField()
    VB12 = models.FloatField()
    VB23 = models.FloatField()
    VB31 = models.FloatField()
    C1 = models.FloatField()
    C2 = models.FloatField()
    C3 = models.FloatField()
    AP1 = models.FloatField()
    AP2 = models.FloatField()
    AP3 = models.FloatField()
    TAP = models.FloatField()
    ApP1 = models.FloatField()
    ApP2 = models.FloatField()
    ApP3 = models.FloatField()
    TApP = models.FloatField()
    R1 = models.FloatField()
    R2 = models.FloatField()
    R3 = models.FloatField()
    TRP = models.FloatField()
    PF1 = models.FloatField()
    PF2 = models.FloatField()
    PF3 = models.FloatField()
    TPF = models.FloatField()
    F1 = models.FloatField()
    F2 = models.FloatField()
    F3 = models.FloatField()
    CN = models.FloatField()
    PF1C = models.FloatField()
    PF2C = models.FloatField()
    PF3C = models.FloatField()
    TPFS = models.FloatField()
    TC = models.FloatField()
    LC = models.FloatField()

class canal7(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()
    V2 = models.FloatField()
    V3 = models.FloatField()
    VB12 = models.FloatField()
    VB23 = models.FloatField()
    VB31 = models.FloatField()
    C1 = models.FloatField()
    C2 = models.FloatField()
    C3 = models.FloatField()
    AP1 = models.FloatField()
    AP2 = models.FloatField()
    AP3 = models.FloatField()
    TAP = models.FloatField()
    ApP1 = models.FloatField()
    ApP2 = models.FloatField()
    ApP3 = models.FloatField()
    TApP = models.FloatField()
    R1 = models.FloatField()
    R2 = models.FloatField()
    R3 = models.FloatField()
    TRP = models.FloatField()
    PF1 = models.FloatField()
    PF2 = models.FloatField()
    PF3 = models.FloatField()
    TPF = models.FloatField()
    F1 = models.FloatField()
    F2 = models.FloatField()
    F3 = models.FloatField()
    CN = models.FloatField()
    PF1C = models.FloatField()
    PF2C = models.FloatField()
    PF3C = models.FloatField()
    TPFS = models.FloatField()
    TC = models.FloatField()
    LC = models.FloatField()


class canal8(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()
    V2 = models.FloatField()
    V3 = models.FloatField()
    VB12 = models.FloatField()
    VB23 = models.FloatField()
    VB31 = models.FloatField()
    C1 = models.FloatField()
    C2 = models.FloatField()
    C3 = models.FloatField()
    AP1 = models.FloatField()
    AP2 = models.FloatField()
    AP3 = models.FloatField()
    TAP = models.FloatField()
    ApP1 = models.FloatField()
    ApP2 = models.FloatField()
    ApP3 = models.FloatField()
    TApP = models.FloatField()
    R1 = models.FloatField()
    R2 = models.FloatField()
    R3 = models.FloatField()
    TRP = models.FloatField()
    PF1 = models.FloatField()
    PF2 = models.FloatField()
    PF3 = models.FloatField()
    TPF = models.FloatField()
    F1 = models.FloatField()
    F2 = models.FloatField()
    F3 = models.FloatField()
    CN = models.FloatField()
    PF1C = models.FloatField()
    PF2C = models.FloatField()
    PF3C = models.FloatField()
    TPFS = models.FloatField()
    TC = models.FloatField()
    LC = models.FloatField()

class canal9(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()
    V2 = models.FloatField()
    V3 = models.FloatField()
    VB12 = models.FloatField()
    VB23 = models.FloatField()
    VB31 = models.FloatField()
    C1 = models.FloatField()
    C2 = models.FloatField()
    C3 = models.FloatField()
    AP1 = models.FloatField()
    AP2 = models.FloatField()
    AP3 = models.FloatField()
    TAP = models.FloatField()
    ApP1 = models.FloatField()
    ApP2 = models.FloatField()
    ApP3 = models.FloatField()
    TApP = models.FloatField()
    R1 = models.FloatField()
    R2 = models.FloatField()
    R3 = models.FloatField()
    TRP = models.FloatField()
    PF1 = models.FloatField()
    PF2 = models.FloatField()
    PF3 = models.FloatField()
    TPF = models.FloatField()
    F1 = models.FloatField()
    F2 = models.FloatField()
    F3 = models.FloatField()
    CN = models.FloatField()
    PF1C = models.FloatField()
    PF2C = models.FloatField()
    PF3C = models.FloatField()
    TPFS = models.FloatField()
    TC = models.FloatField()
    LC = models.FloatField()


class canal10(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()
    V2 = models.FloatField()
    V3 = models.FloatField()
    VB12 = models.FloatField()
    VB23 = models.FloatField()
    VB31 = models.FloatField()
    C1 = models.FloatField()
    C2 = models.FloatField()
    C3 = models.FloatField()
    AP1 = models.FloatField()
    AP2 = models.FloatField()
    AP3 = models.FloatField()
    TAP = models.FloatField()
    ApP1 = models.FloatField()
    ApP2 = models.FloatField()
    ApP3 = models.FloatField()
    TApP = models.FloatField()
    R1 = models.FloatField()
    R2 = models.FloatField()
    R3 = models.FloatField()
    TRP = models.FloatField()
    PF1 = models.FloatField()
    PF2 = models.FloatField()
    PF3 = models.FloatField()
    TPF = models.FloatField()
    F1 = models.FloatField()
    F2 = models.FloatField()
    F3 = models.FloatField()
    CN = models.FloatField()
    PF1C = models.FloatField()
    PF2C = models.FloatField()
    PF3C = models.FloatField()
    TPFS = models.FloatField()
    TC = models.FloatField()
    LC = models.FloatField()


class canal11(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()
    V2 = models.FloatField()
    V3 = models.FloatField()
    VB12 = models.FloatField()
    VB23 = models.FloatField()
    VB31 = models.FloatField()
    C1 = models.FloatField()
    C2 = models.FloatField()
    C3 = models.FloatField()
    AP1 = models.FloatField()
    AP2 = models.FloatField()
    AP3 = models.FloatField()
    TAP = models.FloatField()
    ApP1 = models.FloatField()
    ApP2 = models.FloatField()
    ApP3 = models.FloatField()
    TApP = models.FloatField()
    R1 = models.FloatField()
    R2 = models.FloatField()
    R3 = models.FloatField()
    TRP = models.FloatField()
    PF1 = models.FloatField()
    PF2 = models.FloatField()
    PF3 = models.FloatField()
    TPF = models.FloatField()
    F1 = models.FloatField()
    F2 = models.FloatField()
    F3 = models.FloatField()
    CN = models.FloatField()
    PF1C = models.FloatField()
    PF2C = models.FloatField()
    PF3C = models.FloatField()
    TPFS = models.FloatField()
    TC = models.FloatField()
    LC = models.FloatField()


class canal12(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()
    V2 = models.FloatField()
    V3 = models.FloatField()
    VB12 = models.FloatField()
    VB23 = models.FloatField()
    VB31 = models.FloatField()
    C1 = models.FloatField()
    C2 = models.FloatField()
    C3 = models.FloatField()
    AP1 = models.FloatField()
    AP2 = models.FloatField()
    AP3 = models.FloatField()
    TAP = models.FloatField()
    ApP1 = models.FloatField()
    ApP2 = models.FloatField()
    ApP3 = models.FloatField()
    TApP = models.FloatField()
    R1 = models.FloatField()
    R2 = models.FloatField()
    R3 = models.FloatField()
    TRP = models.FloatField()
    PF1 = models.FloatField()
    PF2 = models.FloatField()
    PF3 = models.FloatField()
    TPF = models.FloatField()
    F1 = models.FloatField()
    F2 = models.FloatField()
    F3 = models.FloatField()
    CN = models.FloatField()
    PF1C = models.FloatField()
    PF2C = models.FloatField()
    PF3C = models.FloatField()
    TPFS = models.FloatField()
    TC = models.FloatField()
    LC = models.FloatField()


class prueba(models.Model):
    tiempo = models.DateTimeField(auto_now=True)
    V1 = models.FloatField()



#Diccionario de Variables

#V1=Voltage Line 1
#V2=Voltage Line 2
#V3=Voltage Line 3
#VB12=Voltage between line 1 and Line 2
#VB23=Voltage between line 2 and Line 3
#VB31=Voltage between line 3 and Line 1
#C1=Current in Line 1
#C2=Current in Line 2
#C3=Current in Line 3
#AP1=Active Power Line 1 (Watt)
#AP2=Active Power Line 2 (Watt)
#AP3=Active Power Line 3 (watt)
#TAP=Total Active Power Line 1+2 +3 (watt)
#ApP1=Apparent Power Line 1 (VA)
#ApP2=Apparent Power Line 2 (VA)
#ApP3=Apparent Power Line 3 (VA)
#TApP=Total Apparent Power Line 1+2+3
#R1=Reactive Power Line 1 (VAR)
#R2=Reactive Power Line 2 (VAR)
#R3=Reactive Power Line 3 (VAR)
#TRP=Total Reactive Power Line 1+2+3
#PF1=Power Factor Line 1 (PF)
#PF2=Power Factor Line 2 (PF)
#PF3=Power Factor Line 3 (PF)
#TPF=Total Power Factor (Line 1+2+3) Absolute (+)
#F1=Frequency Line 1
#F2=Frequency Line 2
#F3=Frequency Line 3
#CN=Current Neutral Line
#PF1C=Power Factor Line 1 (L & C)
#PF2C=Power Factor Line 2 (L & C)
#PF3C=Power Factor Line 3 (L & C)
#TPFS=Total Power Factor (Line 1+2+3) Signed (+/-)
#TC=Total Current in Line 1+2+3
#LC=Leakage Current